class DeviceImportLocators:
    ORG_SELECTOR = "xpath=//*[contains(text(), 'тест андрей')]"
    DEVICES_MENU = "xpath=/html/body/div[1]/div[2]/div/div/div[2]/div/div[2]/ul/li[2]/a"
    IMPORT_AD_BUTTON = "xpath=/html/body/div[1]/div[2]/div/div/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/div/div[2]/div/div[1]/div/a[2]/i"
    SERVER_INPUT = "xpath=/html/body/div[4]/div[2]/div/div/div[2]/form/div[1]/div[2]/div/input"
    USERNAME_INPUT = "xpath=/html/body/div[4]/div[2]/div/div/div[2]/form/div[1]/div[3]/div/input"
    PASSWORD_INPUT = "xpath=/html/body/div[4]/div[2]/div/div/div[2]/form/div[1]/div[4]/div/input"
    SUBMIT_IMPORT_BUTTON = "xpath=/html/body/div[4]/div[2]/div/div/div[2]/form/div[2]/button[1]"
    FILTER_BUTTON = "xpath=/html/body/div[1]/div[2]/div/div/div[2]/div/div[2]/div[1]/div/div[2]/div[1]/i"
    REGISTRATION_DROPDOWN_TOGGLE = "xpath=/html/body/div[1]/div[2]/div/div/div[2]/div/div[2]/div[1]/div/div[2]/form/div[1]/div[1]/div[2]/p/span"
    SELECT_ALL_CHECKBOX = "xpath=/html/body/div[1]/div[2]/div/div/div[2]/div/div[2]/div[1]/div/div[2]/form/div[1]/div[1]/div[2]/div/p[1]/label"
    APPLY_BUTTON = "xpath=/html/body/div[1]/div[2]/div/div/div[2]/div/div[2]/div[1]/div/div[2]/form/div[2]/button[1]"
    RESULT_DOMAIN = "xpath=//*[contains(text(), 'smbdomain.dom')]"
