import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://office.setuplk.ru/Account/Login?returnUrl=%2FClientOrg")
    page.get_by_role("textbox", name="Email").click()
    page.locator("#page-wrapper").click()
    page.locator("#page-wrapper").dblclick()
    page.locator("#page-wrapper").dblclick()
    page.locator("#page-wrapper").click()
    page.get_by_role("link", name=" Администрирование ").click()
    page.get_by_role("link", name=" Системные настройки").click()
    page.locator("#SMTPServer").click()
    page.locator("#SMTPServer").fill("mxz.safib.ru")
    page.locator("#SMTPPort").click()
    page.locator("#SMTPPort").fill("587")
    page.locator("#SMTPLogin").click()
    page.locator("#SMTPLogin").fill("test@safib.ru")
    page.locator("#SMTPPassword").click()
    page.locator("#SMTPPassword").fill("26PatHolPosAmo")
    page.locator("#ServiceEMail").click()
    page.locator("#ServiceEMail").fill("corp@safib.ru")
    page.locator("#TelegramApiId").click()
    page.locator("#TelegramApiId").fill("22979763")
    page.locator("#TelegramApiHash").click()
    page.locator("#TelegramApiHash").fill("ca5f6ae52503eaac4f693b7af94bcd85")
    page.locator("#TelegramPhoneNumber").click()
    page.locator("#TelegramPhoneNumber").fill("89202226365")
    page.get_by_role("button", name="Сохранить").click()
    page.locator("#Server").click()
    page.locator("#Server").fill("")
    page.get_by_text("Тип домена").click()
    page.get_by_text("Тип домена").click()
    page.get_by_text("Тип домена").click()
    page.get_by_text("Тип домена").click()
    page.get_by_text("Тип домена").click()
    page.locator("#Server").click()
    page.locator("#Server").press("ControlOrMeta+м")
    page.locator("#Server").click()
    page.locator("#Server").press("ControlOrMeta+м")
    page.locator("#Server").press("ControlOrMeta+я")
    page.get_by_text("Тип домена").click()
    page.locator("#Server").click()
    page.locator("#Server").press("ControlOrMeta+м")
    page.locator("#Server").press("ControlOrMeta+м")
    page.get_by_role("button", name="Отмена").click()
    page.get_by_role("link", name="").click()
    page.locator("#Server").click()
    page.locator("#Server").fill("dc01.test.local")
    page.locator("#Login").click()
    page.locator("#Login").fill("user1")
    page.locator("#Password").click()
    page.locator("#Password").fill("123")
    page.get_by_label("ДОБАВЛЕНИЕ ПРАВИЛА").get_by_role("button", name="Сохранить").click()
    page.get_by_role("link", name="").click()
    page.locator("#Server").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
