# .github/workflows/test.yml (полная версия)
name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/playwright
          key: ${{ runner.os }}-deps-${{ hashFiles('requirements.txt') }}

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run tests
        env:
          LOGIN: ${{ secrets.LOGIN }}
          CORRECT_PASSWORD: ${{ secrets.CORRECT_PASSWORD }}
          ADMIN_LOGIN: ${{ secrets.ADMIN_LOGIN }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          TESSERACT_PATH: "/usr/bin/tesseract"
        run: |
          pytest tests/ --stand=corp -v --html=report.html

      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: |
            report.html
            screenshots/*